### PR TITLE
Remove dependency on jQuery event alias and deprecated modules

### PR DESCRIPTION
**Pull request by arschmitz**

### CODE REVIEW

**Comment by jzaefferer** [comment]
:+1:

**Comment by staabm** [comment]
This also uplifts the dependency for the required jquery version to `>= 1.7` which should be documented somewhere.

the https://github.com/jquery/jquery-simulate/blob/master/bower.json also defines jquery 1.6.* atm.

**Comment by arschmitz** [comment]
Updated bower.json and added a note about support to the readme

**Comment by scottgonzalez** [comment]
@arschmitz Let's land this.

**Comment by arschmitz** [comment]
wow yeah didnt know this was still out here will get on that

**Pull request merged**
